### ISSUE TITLE
enhancement - add search function

### ISSUE THREAD

**Issue by p-bo** [linuxenko/chkservice#11]
List of units tends be really long - it would be very convenient to hit (for instance) slash (/) key and then write part of unit name / description instead of finding it visually in long list, which is time consuming and prone to overlooking.

**Comment by linuxenko** [comment]
I'll try :smiley:

**Comment by nobk** [comment]
Yes we need search and quick locate feature.

**Comment by linuxenko** [comment]
It has search support since `v0.3`

**Comment by p-bo** [comment]
Great! Thanks a lot :)
