### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by E3V3A** [linuxenko/chkservice#13]
This is a truly excellent tool! 
And (unfortunately!?) also the only one available for Mint 19.1, since BUM is no longer available from apt, so please keep this maintained.  :+1: 

What is the current status for this?

**Comment by linuxenko** [comment]
Trying to figure out which features to implement for, maybe 0.3 version of this. Anyways it seems to be stable.

**Comment by dodona2** [comment]
Thanks Svetlana!

**Comment by linuxenko** [comment]
@dodona2  I hope you've seen my answer about the email in #2 topic ) I want you to know it was an coincidence )
