### ISSUE TITLE
Install on Centos 

### ISSUE THREAD

**Issue by franshesco** [linuxenko/chkservice#6]
Hello, 

It is a good tool. There is a procedure to install it on yum system as centos 7 for example?

**Comment by linuxenko** [comment]
Hi @franshesco . It depends on version of the `libsystemd` installed, it should be greater than `222`, as i know, there is very old version of the `libsystemd` installed by default on `epel7` . You can try [release build](https://github.com/linuxenko/chkservice/releases/tag/0.1) package (does not tested on centos) and report results please.

**Comment by franshesco** [comment]
hi @linuxenko . You are right about libsystemd on epel7. I try the release build but it doesn't work. I have the following errors:
```
error: Failed dependencies:
	libncurses.so.5(NCURSES_5.0.19991023)(64bit) is needed by chkservice-0.1.0-1.x86_64
	libstdc++.so.6(GLIBCXX_3.4.20)(64bit) is needed by chkservice-0.1.0-1.x86_64
	libstdc++.so.6(GLIBCXX_3.4.21)(64bit) is needed by chkservice-0.1.0-1.x86_64
	libsystemd.so.0(LIBSYSTEMD_221)(64bit) is needed by chkservice-0.1.0-1.x86_64
	libtinfo.so.5(NCURSES_TINFO_5.0.19991023)(64bit) is needed by chkservice-0.1.0-1.x86_64
```
Curiously, the dependencies are installed so I think that it is about the old libsystemd version installed on centos 7
