### ISSUE TITLE
ubuntu/debian packages maintatiner needed

### ISSUE THREAD

**Issue by linuxenko** [linuxenko/chkservice#7]

**Comment by linuxenko** [comment]
It seems like people cannot install `chkservice` on `zesty` and `artful` via `ppa` (because there is not builds for them yet)

**Comment by ana-cc** [comment]
Hey, can you remove the debian/ directory from the tarball release? It's easier to package this in Debian this way.

**Comment by linuxenko** [comment]
Hi, @ana-cc. It does not work this way, the `tarball` based on repository files and creates automatically. I can create special `tarballs` for you, and, i think about `0.2` version with bunch of small fixes, what do you think about special tarballs for you, `chkservice-cc-X.Y.tgz` for instance ?

**Comment by ana-cc** [comment]
Hi, thanks for replying. Sorry I spoke too soon, it's actually really easy to work with as it is. So no changes needed.

**Comment by ana-cc** [comment]
Hi, chkservice is now in Debian: https://packages.debian.org/source/sid/chkservice

**Comment by linuxenko** [comment]
Wow  ! :+1:

**Comment by linuxenko** [comment]
It would be nice to update it to the latest version, currently it is `v0.3`.

**Comment by ana-cc** [comment]
This has now been updated in Debian to version 0.3.
